### ISSUE TITLE
Application shows error on any operations if wrong folder was selected previously

### ISSUE THREAD

**Issue by Legionivo** [Gapminder/gapminder-offline#103]
**Steps to reproduce:**
1. Open Gapminder offline application.
2. Open Menu - New Chart - Your data - DDF folder.
3. Select any folder on your computer.
==> Error displayed.
4. Click on **+**  and select any chart from the list.

**Actual result:** 
The same error displayed as previously when incorrect folder was selected. It will show error on any operation you'll try to do.

**Expected result:**
Selected chart should be displayed.

**Comment by buchslava** [comment]
This problem is more complex. I found at least 2 different cases:

1. DDF folder dialog works correctly only once. It was my issue and now it's fixed: https://github.com/Gapminder/gapminder-offline/issues/108

In my mind, next case is depending on vizabi.
2. 
- Open Gapminder offline application.
- Open Menu - New Chart - Your data - DDF folder.
- Select non-ddf (wrong) folder on your computer.
==> Error displayed.
Click on + and select any chart from the list or open new (correct) DDF folder

In this case, you will see a previous error in ANY case even if a tab with the wrong vizabi is closed. I've provided some tests and think it's vizabi's issue because file path in the new model (config) is correct.

![screenshot from 2017-07-27 11-27-09](https://user-images.githubusercontent.com/6974213/28665836-a98c2896-72cd-11e7-8772-e87be09b50f9.png)
![screenshot from 2017-07-27 11-27-53](https://user-images.githubusercontent.com/6974213/28665844-b12d5e12-72cd-11e7-8c6e-4da858e78aa3.png)

So, I guess the problem is: `it's impossible to create a new Vizabi instance after previous Vizabi's error`

@angieskazka @jheeffer what do you think?

cc @k6Labz @kuguarpwnz @Legionivo

**Comment by buchslava** [comment]
@angieskazka it should be closed now, isn't it?

**Comment by angieskazka** [comment]
@buchslava no, this is about reading ddf datasets, we didn't get there yet but i'll give you and update soon, when vizabi is ready for this
