### ISSUE TITLE
Feature: User-friendly DDF validation

### ISSUE THREAD

**Issue by angieskazka** [Gapminder/gapminder-offline#215]

**Comment by buchslava** [comment]
@angieskazka sorry, I forgot... tell me please, do we need a separate menu item for this functionality?

**Comment by angieskazka** [comment]
@buchslava: yes, new menu item and a new modal gialog.
path to the ddf dataset
checkboxes "also generate datapackage" "preserve dataset info from the previous datapackage"
button validate
a view for results: successful
or validation issues as a table

**Comment by buchslava** [comment]
@angieskazka as far as I understand it should be a radio button: "also generate datapackage" "preserve dataset info from the previous datapackage", because these options are mutually exclusive. isn't it?

I would say it can be:
'use current datapackage' [default]
'create new datapackage'

What do you think?
