### ISSUE TITLE
Cannot get X & Y axis to use custom data when creating chart with own data csv

### ISSUE THREAD

**Issue by ayal01** [Gapminder/gapminder-offline#220]
Hi, 

Great tool!

When using custom data csv, X & Y axis selection is limited to time field only. Other numeric fields are not being picked up.

CSV file example:
Country,Month,growth,value,rank,Region
QLGC,2001-12,44,0,33,Technology
LEHMQ,2001-12,44,87,50,Financials
CIN,2001-12,50,40,48,Utilities
MCK,2001-12,27,26,27,Healthcare
COF,2001-12,63,51,60,Financials
QLGC,2002-01,47,0,35,Technology
...

Size and Colour selection do see the other fields. Expect to see growht,value and rank fields accessible in axis selection dropdown.

Thanks.

**Comment by angieskazka** [comment]
@ayal01 hi! this means some of the values in "growth","value","rank" columns are interpreted as strings. Please look through your table and try to find these. It can be "..." instead of empty values (should be just empty), or some other non-numeric and non-empty info.

month are broken now in v3.1.0, but next release fixes them

**Comment by angieskazka** [comment]
closing this. please contact me if this is still an issue. angie@gapminder.org
