### ISSUE TITLE
add multi-language support (language picker)

### ISSUE THREAD

**Issue by buchslava** [Gapminder/gapminder-offline#278]

**Comment by angieskazka** [comment]
improvements request

1) different languages require different fonts because of variations in optical density. We should have the app switch main font depending on the language in use. This issue was solved on tools page, it also has a nice font for cyrillic scrtips, please look there
![image](https://user-images.githubusercontent.com/3648190/51439378-58866c00-1cdf-11e9-9e25-a56eb39b1f56.png)

2) Make file names and format same as in tools page. Borrow some language strings, such as chart names :) 
https://github.com/Gapminder/tools-page/tree/development/src/assets/i18n 

3) Add arabic as soon as possible, so we can start designing and testing rtl layouts. See how vizabi and tools page changes UI for Arabic, offline app should do the similar thing

**Comment by buchslava** [comment]
> 1. different languages require different fonts because of variations in optical density. We should have the app switch main font depending on the language in use. This issue was solved on tools page, it also has a nice font for cyrillic scrtips, please look there
>    ![image](https://user-images.githubusercontent.com/3648190/51439378-58866c00-1cdf-11e9-9e25-a56eb39b1f56.png)

@angieskazka I don't see any serious difference between tools-page and gapminder-offline, I use exactly the same fonts and their combination (at least, for body). Tell me please what should I do?
![screenshot from 2019-01-21 12-25-27](https://user-images.githubusercontent.com/6974213/51469299-bebfcd00-1d79-11e9-9c57-e3e767f7c652.png)
