### ISSUE TITLE
Feature: explore file extensions other than JSON ...

### ISSUE THREAD

**Issue by buchslava** [Gapminder/gapminder-offline#75]
Feature: explore file extensions other than JSON to have it bound to the installed app, so that by clicking the file, Gapminder offline will launch and open that file.

**Comment by angieskazka** [comment]
@buchslava Example: 
a user can save a file in Microsoft Word, it saves as docx
by clicking that file, it opens associated application and then opens itself inside associated application

this issue is to explore ways to introduce the same behavior in our offline app
because i've seen people clicking on json files after they've saved them, and these jsons won't open automatically of course
